<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="17808" started-at="2020-01-13T10:03:56Z" finished-at="2020-01-13T10:04:14Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="17808" started-at="2020-01-13T10:03:56Z" finished-at="2020-01-13T10:04:14Z">
      <class name="com.hellofresh.challenge.tests.Test_1_SignIn">
        <test-method status="PASS" signature="setUpTestData()[pri:0, instance:com.hellofresh.challenge.tests.Test_1_SignIn@2cbb3d47]" name="setUpTestData" is-config="true" duration-ms="449" started-at="2020-01-13T10:03:56Z" finished-at="2020-01-13T10:03:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestData -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hellofresh.challenge.tests.Test_1_SignIn@2cbb3d47]" name="setUp" is-config="true" duration-ms="4272" started-at="2020-01-13T10:03:56Z" finished-at="2020-01-13T10:04:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validSignInTest()[pri:0, instance:com.hellofresh.challenge.tests.Test_1_SignIn@2cbb3d47]" name="validSignInTest" duration-ms="12025" started-at="2020-01-13T10:04:00Z" description="Valid Sign In Test" finished-at="2020-01-13T10:04:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.hellofresh.challenge.pages.BasePage.assertTrueContains(BasePage.java:65)
at com.hellofresh.challenge.pages.SignInPage.verifyInfoAccount(SignInPage.java:122)
at com.hellofresh.challenge.tests.Test_1_SignIn.validSignInTest(Test_1_SignIn.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validSignInTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.hellofresh.challenge.tests.Test_1_SignIn@2cbb3d47]" name="cleanUp" is-config="true" duration-ms="855" started-at="2020-01-13T10:04:13Z" finished-at="2020-01-13T10:04:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.hellofresh.challenge.tests.Test_1_SignIn -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
